export enum GENRES {
    COMEDY= 'Comedy',
    FANTASY = 'Fantasy',
    CRIME = 'Crime',
    DRAMA = 'Drama',
    MUSIC = 'Music',
    ADVENTURE = 'Adventure',
    HISTORY = 'History',
    THRILLER = 'Thriller',
    ANIMATION = 'Animation',
    FAMILY = 'Family',
    MYSTERY = 'Mystery',
    BIOGRAPHY = 'Biography',
    ACTION = 'Action',
    FILM_NOIR = 'Film-Noir',
    ROMANCE = 'Romance',
    SCI_FI = 'Sci-Fi',
    WAR = 'War',
    WESTERN = 'Western',
    HORROR = 'Horror',
    MUSICAL = 'Musical',
    SPORT = 'Sport',
}